name: JSON SyntaxCheck
on: [push]

jobs:
  jsontest:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: shogo82148/actions-setup-perl@v1.10.0
      with:
        perl-version: '5.26'
    - run: cpanm --notest --installdeps .
    - name: run prove (testscripts)
      run: |
        prove -lr --ext=.pl t
